name: Quality Assurance
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  main:
    strategy:
      matrix:
        script: ["yarn eslint .", "yarn tsc", "yarn prettier . --check"]
      # Default behaviour is "true" - which cancels all queued or in-progress jobs when one fails, which we don't want.
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Checking out git
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Script
        run: ${{ matrix.script }}
